"use client";

import { createContext, useContext, useEffect, useState, ReactNode } from "react";

export type Theme = "ocean" | "midnight" | "abyss" | "inferno";
export type Lang = "en" | "ru";

interface SettingsCtx {
  theme: Theme;
  lang: Lang;
  setTheme: (t: Theme) => void;
  setLang: (l: Lang) => void;
}

const Ctx = createContext<SettingsCtx>({
  theme: "ocean", lang: "en",
  setTheme: () => {}, setLang: () => {},
});

export function SettingsProvider({ children }: { children: ReactNode }) {
  const [theme, setThemeState] = useState<Theme>("ocean");
  const [lang, setLangState] = useState<Lang>("en");
  const [settingsReady, setSettingsReady] = useState(false);

  useEffect(() => {
    const t = localStorage.getItem("sw_theme") as Theme | null;
    const l = localStorage.getItem("sw_lang") as Lang | null;
    if (t) setThemeState(t);
    if (l) setLangState(l);
    setSettingsReady(true);
  }, []);

  useEffect(() => {
    if (!settingsReady) return;
    document.documentElement.setAttribute("data-theme", theme);
  }, [theme, settingsReady]);

  const setTheme = (t: Theme) => {
    setThemeState(t);
    localStorage.setItem("sw_theme", t);
  };

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("sw_lang", l);
  };

  return <Ctx.Provider value={{ theme, lang, setTheme, setLang }}>{children}</Ctx.Provider>;
}

export const useSettings = () => useContext(Ctx);

export const THEMES: { id: Theme; label: string; color: string }[] = [
  { id: "ocean",    label: "Ocean",    color: "#00d4ff" },
  { id: "midnight", label: "Midnight", color: "#b47fff" },
  { id: "abyss",    label: "Abyss",    color: "#00ff88" },
  { id: "inferno",  label: "Inferno",  color: "#ff6600" },
];

type Tr = Record<string, string>;

export const TR: Record<Lang, Tr> = {
  en: {
    subtitle_bot:    "Play vs AI. Save result onchain after the match.",
    subtitle_friend: "Play with a friend. Each captain saves their own result.",
    subtitle_wager:  "Bet USDC, winner takes 90%.",
    mode_bot:        "Bot",    mode_bot_hint:    "Solo vs AI",
    mode_friend:     "Friend", mode_friend_hint: "PvP via invite ID",
    mode_wager:      "Wager",  mode_wager_hint:  "USDC stakes",
    connect:         "Connect Wallet",
    play_bot:        "Play vs Bot",
    create_game:     "Create Game",
    join:            "Join",
    joining:         "Joining...",
    private_game:    "Private game (invite only)",
    join_by_id:      "or join by ID",
    game_id:         "Game ID",
    open_games:      "Open Games",
    no_open_games:   "No open games. Create one!",
    checkin_btn:     "Daily Check-in",
    checkin_done:    "Checked in! Streak:",
    checkin_free:    "FREE",
    leaderboard:     "Leaderboard",
    profile:         "Profile",
    wins:            "Wins",
    shots:           "Shots",
    streak:          "Streak",
    checkins:        "Check-ins",
    onchain_winrate: "Onchain winrate",
    net_pnl:         "Net P&L (wager)",
    unclaimed:       "Unclaimed Prizes",
    refundable:      "Refundable Games",
    claim:           "Claim",
    refund:          "Refund",
    footer:          "Sea Battle on Base",
    settings_title:  "Settings",
    theme_label:     "Theme",
    lang_label:      "Language",
    referrals:       "Referrals",
    referrals_sub:   "1,000 pts per player · 10% of their points",
    referrals_desc:  "Invite a player — get 1,000 pts when they play their first game, plus 10% of all their game points forever.",
    direct_link:     "Direct link",
    copy:            "Copy",
    copied_ok:       "Copied!",
    invited:         "Invited",
    playing:         "Playing",
    pending_ref:     "Pending",
    recent_games:    "Recent Games",
    hist_loading:    "Loading...",
    hist_empty:      "No finished games yet.",
    weekly_quests:   "Weekly Quests",
    quests_loading:  "Loading quests...",
    quests_ready:    "ready",
    quest_claimed:   "Claimed ✓",
    quest_claim:     "Claim",
    quest_claim_free:"Claim · FREE",
    quest_claim_tx:  "Claim (1 tx)",
    quest_processing:"Processing...",
    quest_footer:    "claimed · resets next Monday",
    quest_not_ready: "Quest is not ready yet",
    quest_rerolled_into:"Rerolled into",
    quest_reroll_failed:"Reroll failed",
    quest_reroll_one:"reroll",
    quest_rerolling:"Rerolling...",
    home_play:       "Play Now",
    home_quests:     "Quests",
    home_leaderboard:"Leaderboard",
    home_shop:       "Shop",
    home_play_bot:       "Play vs Bot",
    home_play_bot_sub:   "Challenge AI opponents",
    home_play_friend:    "Play with Friend",
    home_play_friend_sub:"Invite a captain by ID",
    home_play_wager:     "Play on USDC",
    home_play_wager_sub: "Stake & winner takes 90%",
    home_play_challenge: "Async Challenge",
    home_play_challenge_sub: "One challenger attacks your fleet",
    home_checkin_title:  "Daily Check-in",
    home_checkin_sub:    "Claim your daily reward",
    home_checkin_done:   "Done today",
    home_quests_sub:     "Weekly + global rewards",
    home_profile_title:  "Profile",
    home_profile_sub:    "Stats & achievements",
    home_history_title:  "Recent Games",
    home_history_sub:    "View your battle history",
    home_referrals_title:"Referrals",
    home_leaderboard_sub:"Top captains · see who's #1",
    home_welcome_pc: "Welcome, Captain",
    home_pc_hint:    "Connect your wallet to deploy your fleet onchain",
    home_pc_features:"Free vs AI · USDC wagers · Daily rewards",
    back:            "Back",
    shop_title:      "Shop",
    shop_subtitle:   "Boosters & rewards",
    shop_bomb_title: "Bomb 3×3",
    shop_bomb_desc:  "Fires a 3×3 area in a single shot. Use one per wager game.",
    shop_bomb_price: "2 USDC each",
    shop_bomb_buy:   "Buy +1",
    shop_bomb_owned: "Owned",
    shop_bomb_inventory: "In inventory",
    shop_bomb_buying: "Buying...",
    shop_bomb_approve: "Approve USDC...",
    shop_bomb_pending:"Confirm in wallet...",
    shop_checkin_title: "Daily Check-in",
    shop_checkin_desc:  "Free reward — every day. Streak bonus every 5 days.",
    shop_checkin_done:  "Already checked in today",
    welcome_checkin:    "Daily Check-in",
    welcome_checkin_sub:"Claim your free daily reward",
    welcome_skip:       "Skip",
    lb_subtitle:        "Top players by points",
    lb_player:          "Player",
    lb_points:          "Points",
    lb_help_title:      "How points work",
    lb_help_win:        "for winning a game",
    lb_help_hit:        "for each hit on enemy ship",
    lb_help_checkin:    "daily check-in (base reward)",
    lb_help_streak:     "every 5 consecutive days, reward increases by +5",
    lb_help_streak_label:"Streak bonus",
    lb_help_note:       "Check-in resets daily at 00:00 UTC.",
    lb_empty:           "No players yet. Be the first!",
    you_label:          "you",
    bot_waters:         "Bot Waters",
    your_fleet:         "Your Fleet",
    your_board:         "Your Board",
    bot_fleet:          "Bot Fleet",
    fire_at:            "Fire at",
    bot_thinking:       "Bot is thinking...",
    select_cell:        "Select a cell to fire",
    waiting:            "Waiting...",
    your_turn:          "Your Turn",
    turn_your:          "YOUR TURN",
    turn_bot:           "BOT TURN",
    turn_bot_thinking:  "BOT THINKING",
    you_short:          "You",
    bot_short:          "Bot",
    main_menu:          "Main Menu",
    save_result_tx:     "SAVE RESULT (1 TX)",
    confirming:         "CONFIRMING…",
    bot_msg_saved:      "Saved onchain ✓ The ocean is yours.",
    bot_msg_win:        "All bot ships sunk! Save the result to claim your points.",
    bot_msg_lose:       "The bot destroyed your fleet. Try again, captain.",
    play_modal_close:   "Close",
    play_modal_kicker:  "Select mode",
    play_modal_title:   "Choose battle type",
    play_modal_select:  "Select",
    mobile_home:        "Home",
    mobile_quests:      "Quests",
    mobile_profile:     "Profile",
    mobile_shop:        "Shop",
    mobile_top:         "Top",
    mobile_pnl:         "PNL",
    mobile_wins:        "Wins",
    mobile_recent:      "Recent",
    mobile_your_fleet:  "Your Fleet",
    mobile_enemy_grid:  "Enemy Grid",
    mobile_scanning:    "Scanning E1 - fleet ready",
    loss:               "Loss",
    win_short:          "Win",
    loss_short:         "Loss",
    ai_bot:             "AI Bot",
    pvp:                "PvP",
    wager_upper:        "Wager",
    bot_upper:          "Bot",
    social_join:        "Join the channel",
    social_watch:       "Watch & subscribe",
    shop_eyebrow:       "Armory Market",
    shop_page_subtitle: "Tactical boosters and wager inventory",
    shop_connect_hint:  "Connect Wallet to buy, activate and claim rewards.",
    shop_status_label:  "Shop status",
    shop_boost:         "Boost",
    shop_boost_inactive:"Inactive",
    shop_boost_until:   "x2 until",
    shop_season:        "Battle Pass",
    shop_level:         "Level",
    shop_xp:            "XP",
    shop_bombs:         "Bombs",
    shop_featured:      "Featured",
    shop_featured_desc: "The weekly armory rotation. Items work in Bot/Friend modes and regular progression.",
    shop_activate:      "Activate",
    shop_working:       "Working...",
    shop_owned:         "Owned",
    shop_pts:           "pts",
    contract_not_deployed:"Contract not deployed",
    tx_rejected:        "Rejected",
    checkin_already_done:"Already checked in today",
    streak_freeze_used: "freeze used",
    bomb_unit_one:      "bomb",
    bomb_unit_many:     "bombs",
    wallet_menu:        "Wallet",
    wallet_copy_address:"Copy address",
    wallet_disconnect:  "Disconnect",
    shop_item_added:    "Item added to inventory",
    shop_purchase_failed:"Purchase failed",
    shop_double_activated:"Double Points activated",
    shop_activation_failed:"Activation failed",
    shop_reward_claimed:"Battle Pass reward claimed",
    shop_claim_failed:  "Claim failed",
    shop_items_load_failed:"Could not load shop items",
    shop_season_desc:   "A 100-level reward track for hits, wins and daily check-ins. Ends July 18, 2026 at 00:00 UTC.",
    shop_xp_to_level:   "XP to level",
    shop_complete:      "Complete",
    shop_claimed:       "Claimed",
    shop_claiming:      "Claiming...",
    shop_locked:        "Locked",
    shop_inventory:     "Inventory",
    shop_inventory_desc:"Rerolls are used inside Weekly Quests. Streak Freeze is passive.",
    shop_featured_armory:"Featured Armory",
    shop_open_shop:     "Open Shop",
    season_route:       "Battle Pass",
    season_ends:        "Ends Jul 18, 2026 at 00:00 UTC",
    season_per_hit:     "per hit",
    season_per_win:     "per win",
    season_checkin:     "check-in",
    season_reward:      "reward",
    season_complete:    "Battle Pass complete",
    tier_premium:       "Premium",
    tier_legendary:     "Legendary",
    tier_epic:          "Epic",
    tier_rare:          "Rare",
    tier_locked:        "Locked",
  },
  ru: {
    subtitle_bot:    "Играй против ИИ. Запиши результат в блокчейн после матча.",
    subtitle_friend: "Играй с другом. Каждый капитан сохраняет свой результат.",
    subtitle_wager:  "Ставь USDC — победитель забирает 90%.",
    mode_bot:        "Бот",    mode_bot_hint:    "Соло против ИИ",
    mode_friend:     "Друг",   mode_friend_hint: "PvP по ID приглашения",
    mode_wager:      "Ставка", mode_wager_hint:  "Ставки в USDC",
    connect:         "Подключить кошелёк",
    play_bot:        "Играть с ботом",
    create_game:     "Создать игру",
    join:            "Войти",
    joining:         "Подключение...",
    private_game:    "Приватная игра (по приглашению)",
    join_by_id:      "или войти по ID",
    game_id:         "ID игры",
    open_games:      "Открытые игры",
    no_open_games:   "Нет открытых игр. Создай первым!",
    checkin_btn:     "Ежедневный чекин",
    checkin_done:    "Зачекинился! Серия:",
    checkin_free:    "БЕСПЛАТНО",
    leaderboard:     "Таблица лидеров",
    profile:         "Профиль",
    wins:            "Победы",
    shots:           "Выстрелы",
    streak:          "Серия",
    checkins:        "Чекины",
    onchain_winrate: "Ончейн винрейт",
    net_pnl:         "Прибыль/убыток",
    unclaimed:       "Невостребованные призы",
    refundable:      "Возврат ставок",
    claim:           "Получить",
    refund:          "Вернуть",
    footer:          "Sea Battle на Base",
    settings_title:  "Настройки",
    theme_label:     "Тема",
    lang_label:      "Язык",
    referrals:       "Рефералы",
    referrals_sub:   "1 000 pts за игрока · 10% с их очков",
    referrals_desc:  "Пригласи игрока — получи 1 000 pts когда он сыграет первую игру, плюс 10% от всех его игровых очков навсегда.",
    direct_link:     "Прямая ссылка",
    copy:            "Копировать",
    copied_ok:       "Скопировано!",
    invited:         "Приглашено",
    playing:         "Играют",
    pending_ref:     "Ожидают",
    recent_games:    "История игр",
    hist_loading:    "Загрузка...",
    hist_empty:      "Нет завершённых игр.",
    weekly_quests:   "Еженедельные квесты",
    quests_loading:  "Загрузка квестов...",
    quests_ready:    "готово",
    quest_claimed:   "Получено ✓",
    quest_claim:     "Получить",
    quest_claim_free:"Получить · БЕСПЛАТНО",
    quest_claim_tx:  "Получить (1 тx)",
    quest_processing:"Обработка...",
    quest_footer:    "получено · сброс в понедельник",
    quest_not_ready: "Квест еще не готов",
    quest_rerolled_into:"Заменено на",
    quest_reroll_failed:"Реролл не удался",
    quest_reroll_one:"реролл",
    quest_rerolling:"Меняем...",
    home_play:       "Играть",
    home_quests:     "Квесты",
    home_leaderboard:"Таблица лидеров",
    home_shop:       "Магазин",
    home_play_bot:       "Играть с ботом",
    home_play_bot_sub:   "Бой против ИИ",
    home_play_friend:    "Играть с другом",
    home_play_friend_sub:"Пригласить капитана по ID",
    home_play_wager:     "Играть на USDC",
    home_play_wager_sub: "Ставка, победитель забирает 90%",
    home_play_challenge: "Челлендж",
    home_play_challenge_sub: "Один игрок атакует твой флот",
    home_checkin_title:  "Ежедневный чекин",
    home_checkin_sub:    "Забери ежедневную награду",
    home_checkin_done:   "Сделано сегодня",
    home_quests_sub:     "Еженедельные + глобальные награды",
    home_profile_title:  "Профиль",
    home_profile_sub:    "Статистика и достижения",
    home_history_title:  "История игр",
    home_history_sub:    "Посмотри свои битвы",
    home_referrals_title:"Рефералы",
    home_leaderboard_sub:"Топ капитанов · кто №1",
    home_welcome_pc: "Добро пожаловать, капитан",
    home_pc_hint:    "Подключи кошелёк, чтобы развернуть флот в блокчейне",
    home_pc_features:"Бесплатно с ИИ · Ставки в USDC · Ежедневные награды",
    back:            "Назад",
    shop_title:      "Магазин",
    shop_subtitle:   "Бустеры и награды",
    shop_bomb_title: "Бомба 3×3",
    shop_bomb_desc:  "Бьёт по области 3×3 одним выстрелом. По одной на wager-игру.",
    shop_bomb_price: "2 USDC за штуку",
    shop_bomb_buy:   "Купить +1",
    shop_bomb_owned: "Куплено",
    shop_bomb_inventory: "В инвентаре",
    shop_bomb_buying: "Покупка...",
    shop_bomb_approve: "Одобрение USDC...",
    shop_bomb_pending:"Подтверди в кошельке...",
    shop_checkin_title: "Ежедневный чекин",
    shop_checkin_desc:  "Бесплатная награда каждый день. Бонус серии каждые 5 дней.",
    shop_checkin_done:  "Уже зачекинился сегодня",
    welcome_checkin:    "Ежедневный чекин",
    welcome_checkin_sub:"Забери бесплатную ежедневную награду",
    welcome_skip:       "Пропустить",
    lb_subtitle:        "Топ игроков по очкам",
    lb_player:          "Игрок",
    lb_points:          "Очки",
    lb_help_title:      "Как начисляются очки",
    lb_help_win:        "за победу в игре",
    lb_help_hit:        "за каждое попадание по кораблю",
    lb_help_checkin:    "ежедневный чекин (базовая награда)",
    lb_help_streak:     "каждые 5 дней подряд награда растёт на +5",
    lb_help_streak_label:"Бонус серии",
    lb_help_note:       "Чекин сбрасывается ежедневно в 00:00 UTC.",
    lb_empty:           "Игроков пока нет. Будь первым!",
    you_label:          "ты",
    bot_waters:         "Воды бота",
    your_fleet:         "Твой флот",
    your_board:         "Твоё поле",
    bot_fleet:          "Флот бота",
    fire_at:            "Огонь по",
    bot_thinking:       "Бот думает...",
    select_cell:        "Выбери клетку для выстрела",
    waiting:            "Ожидание...",
    your_turn:          "Твой ход",
    turn_your:          "ТВОЙ ХОД",
    turn_bot:           "ХОД БОТА",
    turn_bot_thinking:  "БОТ ДУМАЕТ",
    you_short:          "Ты",
    bot_short:          "Бот",
    main_menu:          "В меню",
    save_result_tx:     "СОХРАНИТЬ РЕЗУЛЬТАТ (1 TX)",
    confirming:         "ПОДТВЕРЖДЕНИЕ…",
    bot_msg_saved:      "Сохранено в блокчейн ✓ Океан твой.",
    bot_msg_win:        "Все корабли бота потоплены! Сохрани результат, чтобы получить очки.",
    bot_msg_lose:       "Бот уничтожил твой флот. Попробуй ещё раз, капитан.",
    play_modal_close:   "Закрыть",
    play_modal_kicker:  "Выбор режима",
    play_modal_title:   "Выбери тип боя",
    play_modal_select:  "Выбрать",
    mobile_home:        "Главная",
    mobile_quests:      "Квесты",
    mobile_profile:     "Профиль",
    mobile_shop:        "Магазин",
    mobile_top:         "Топ",
    mobile_pnl:         "PNL",
    mobile_wins:        "Победы",
    mobile_recent:      "История",
    mobile_your_fleet:  "Твой флот",
    mobile_enemy_grid:  "Сетка врага",
    mobile_scanning:    "Скан E1 - флот готов",
    loss:               "Поражения",
    win_short:          "Победа",
    loss_short:         "Поражение",
    ai_bot:             "ИИ бот",
    pvp:                "PvP",
    wager_upper:        "Ставка",
    bot_upper:          "Бот",
    social_join:        "Вступить в канал",
    social_watch:       "Смотреть и подписаться",
    shop_eyebrow:       "Арсенал",
    shop_page_subtitle: "Тактические бустеры и инвентарь ставок",
    shop_connect_hint:  "Подключи кошелёк, чтобы покупать, активировать и получать награды.",
    shop_status_label:  "Статус магазина",
    shop_boost:         "Буст",
    shop_boost_inactive:"Неактивен",
    shop_boost_until:   "x2 до",
    shop_season:        "Battle Pass",
    shop_level:         "Уровень",
    shop_xp:            "XP",
    shop_bombs:         "Бомбы",
    shop_featured:      "Витрина",
    shop_featured_desc: "Еженедельная ротация арсенала. Предметы работают в режиме с ботом/другом и обычном прогрессе.",
    shop_activate:      "Активировать",
    shop_working:       "В работе...",
    shop_owned:         "Есть",
    shop_pts:           "pts",
    contract_not_deployed:"Контракт не задеплоен",
    tx_rejected:        "Отклонено",
    checkin_already_done:"Сегодня уже был чекин",
    streak_freeze_used: "использована защита серии",
    bomb_unit_one:      "бомба",
    bomb_unit_many:     "бомбы",
    wallet_menu:        "Кошелёк",
    wallet_copy_address:"Скопировать адрес",
    wallet_disconnect:  "Отключить",
    shop_item_added:    "Предмет добавлен в инвентарь",
    shop_purchase_failed:"Покупка не удалась",
    shop_double_activated:"Двойные очки активированы",
    shop_activation_failed:"Активация не удалась",
    shop_reward_claimed:"Награда Battle Pass получена",
    shop_claim_failed:  "Не удалось получить",
    shop_items_load_failed:"Не удалось загрузить предметы",
    shop_season_desc:   "100 уровней наград за попадания, победы и ежедневные чекины. Завершение: 18.07.2026 в 00:00 UTC.",
    shop_xp_to_level:   "XP до уровня",
    shop_complete:      "Завершено",
    shop_claimed:       "Получено",
    shop_claiming:      "Получаем...",
    shop_locked:        "Закрыто",
    shop_inventory:     "Инвентарь",
    shop_inventory_desc:"Реролл используется в недельных квестах. Защита серии работает пассивно.",
    shop_featured_armory:"Витрина арсенала",
    shop_open_shop:     "Открыть магазин",
    season_route:       "Battle Pass",
    season_ends:        "До 18.07.2026 00:00 UTC",
    season_per_hit:     "за попадание",
    season_per_win:     "за победу",
    season_checkin:     "за чекин",
    season_reward:      "награда",
    season_complete:    "Battle Pass завершён",
    tier_premium:       "Премиум",
    tier_legendary:     "Легендарный",
    tier_epic:          "Эпический",
    tier_rare:          "Редкий",
    tier_locked:        "Закрыто",
  },
};
